### ISSUE TITLE
Highlight types based on syntax

### ISSUE THREAD

**Issue by copy** [ocaml/vim-ocaml#11]
Currently there's a hard-coded list of built-in type names that are highlighted specially even when the name is used as an identifier. Custom type names, on the other hand, are not highlighted. 

See:

![screenshot_2016-07-08_00-59-50](https://cloud.githubusercontent.com/assets/1816456/16672617/8b912cba-44a7-11e6-8c71-7d06fb5a5056.png)

``` ocaml
type foo = {
  a: int;
  b: bar;
}

let string = string_of_int
```

**Comment by rdavison** [comment]
Although this might be possible from within a type definition, like in your example, I can't think of a way of doing this using vim's regular expresions to highlight types across the codebase without using a more powerful tool like Merlin to parse the source code and return all the tokens and how they should be highlighted.

**Comment by struktured** [comment]
+1 this would be a great addition if such a thing existed but I agree it requires compiler symbols to work properly.

**Comment by rdavison** [comment]
I've dug around in the source code of merlin and it appears there might be a stubbed out place where such a thing could go https://github.com/ocaml/merlin/blob/master/src/frontend/query_commands.ml#L140

Not sure what the plan is for that particular query command, but I could portentially see that as being our hook for better syntax highlighting

**Comment by copy** [comment]
This will probably be supported by the [tree-sitter](https://github.com/tree-sitter/tree-sitter) project. There's already an [OCaml grammar](https://github.com/tree-sitter/tree-sitter-ocaml) and a [PR for neovim](https://github.com/neovim/neovim/pull/9219).

**Comment by Maelan** [comment]
tree-sitter should be the definitive answer to this. However it is not available in Neovim yet, let alone plain Vim.

FYI, I am hacking `runtime/syntax/ocaml.vim` to highlight types separately from expressions. It is very ad hoc but approximately works, with some corner cases. I will submit a PR at some point.

**Comment by XVilka** [comment]
Tree-sitter is planned for NeoVim 0.5 version: https://github.com/neovim/neovim/pull/10124

**Comment by undu** [comment]
There's an [intention](https://github.com/tree-sitter/tree-sitter-ocaml/issues/40#issuecomment-676519926) to have a separate parser for `.ml` and `.mli` (and there's a specialized one for [.mll](https://github.com/atom-ocaml/tree-sitter-ocamllex)).

I'm double checking how nvim-treesitter will handle with this, we might need to have one filetype per file extension to support multiple tree-sitter parsers instead of using `ocaml` for all of them.

**Comment by rgrinberg** [comment]
I think this can safely be closed. Let's keep the regex based syntax highlighting simple and let the tree sitter grammar handle complex cases.

**Comment by copy** [comment]
> I think this can safely be closed. Let's keep the regex based syntax highlighting simple and let the tree sitter grammar handle complex cases.

Agreed!
