### ISSUE TITLE
errorformat won't be valid for multiline errors after ocaml 4.09

### ISSUE THREAD

**Issue by Khady** [ocaml/vim-ocaml#35]
I sent a change to the OCaml compiler to change the format of the error messages https://github.com/ocaml/ocaml/pull/8541. It means that messages printed by OCaml >= 4.09 won't be parsed properly by this plugin.

The change affects the messages that are on multiple lines. The message now contains the first and last lines. Also the second part of the characters section is no longer a byte offset, it is the position on the last line.

Here is an exemple.

```
File "robustmatch.ml", lines 33-37, characters 6-23:
 9 | ......match t1, t2, x with
10 |       | AB, AB, A -> ()
11 |       | MAB, _, A -> ()
12 |       | _,  AB, B -> ()
13 |       | _, MAB, B -> ()
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
(AB, MAB, A)
```

Tuareg has a list of compilation messages that can be used for reference: https://github.com/Chris00/tuareg/blob/master/compilation.txt

**Comment by trefis** [comment]
I don't know how vim gets the errors from the compiler (I don't use this feature of the plugin), but there is a flag to the compiler to get the "short" errors (i.e. same format as before) that should be used when getting errors inside the editor.

**Comment by Khady** [comment]
https://caml.inria.fr/pub/docs/manual-ocaml/native.html#sec311

The flag is `-error-style`, right?

**Comment by trefis** [comment]
That's right.
