### ISSUE TITLE
ocaml toplevel filetype

### ISSUE THREAD

**Issue by nilsbecker** [ocaml/vim-ocaml#55]
i often write scratch script files that contain code snippets for use in utop. i copy-and-paste these files, or more conveniently, i use vim-slime to automatically pipe the snippets to utop running within tmux. this is a convenient code-block evaluation setup.

utop also writes its own history to such script file when using `#utop_save`. 

it would be nice if vim-ocaml could provide an ocaml-toplevel filetype for such script files. the only (afaics) change to the regular ocaml filetype would be to allow toplevel directives `#require, #help, #pwd` and so on as valid syntax.

afaik, there is no standard file extension for toplevel script files; the user would have to set the filetype manually i fear.

**Comment by mmottl** [comment]
There is already an `ocamlScript` syntax group in the syntax file for OCaml.  It contains, among other things, `#require`.  Please feel free to submit a patch for any missing toplevel directives.  It's ok to add support for `utop` directives there, too.

**Comment by nilsbecker** [comment]
ah ok. in fact i now noticed that `#install_printer` is correctly highlighted in my script file. however, i get an error mark in the leftmost column, identified as `Syntax error`. i guess this comes from the ALE plugin then. ALEInfo says:
```
 Current Filetype: ocaml
Available Linters: ['merlin', 'ols']
  Enabled Linters: ['merlin', 'ols']  
```
and a lot of other stuff. would it make sense to open an issue at merlin?

**Comment by mmottl** [comment]
I guess Merlin should keep track of toplevel syntax, too, at least to ignore it if unsupported.  Feel free to submit a report with them.
