### ISSUE TITLE
open struct end

### ISSUE THREAD

**Issue by Et7f3** [ocaml/vim-ocaml#56]
![image](https://user-images.githubusercontent.com/29592775/86502215-1e107200-bda1-11ea-8562-c37a35bc678f.png)
It doesn't handle anonymous module.

**Comment by mmottl** [comment]
True, but I have unfortunately no time right now to look into this.  Maybe someone else can give it a try?  Please feel free to submit a patch!

**Comment by Et7f3** [comment]
I have tried but I didn't find much info about the syntax. For instance I don't understand what is \<open\> instead of open. So I don't think I can help

**Comment by mmottl** [comment]
I've just tried this and found that it actually works for me.  I'm not sure whether there is any other configuration option that I'm using that makes it work, but it doesn't seem to be a problem with the current syntax file.  I'll close this for now.
