### ISSUE TITLE
Dune: support comments that start with multiple semicolons

### ISSUE THREAD

**Issue by cwfoo** [ocaml/vim-ocaml#65]
Add support for comments that start with multiple semicolons. Patch for [ftplugin/dune.vim](
https://github.com/ocaml/vim-ocaml/blob/ba6a32d0d079b3670cc3c02257dccea4808fdfa1/ftplugin/dune.vim):

```diff
diff --git a/ftplugin/dune.vim b/ftplugin/dune.vim
index 86c99c0..2ef51a7 100644
--- a/ftplugin/dune.vim
+++ b/ftplugin/dune.vim
@@ -15,6 +15,6 @@ set lisp
 
 " Comment string
 setl commentstring=;\ %s
-setl comments=:;
+setl comments=n:;
 
 setl iskeyword+=#,?,.,/
```

A similar change may be appropriate for [ftplugin/sexplib.vim](https://github.com/ocaml/vim-ocaml/blob/ba6a32d0d079b3670cc3c02257dccea4808fdfa1/ftplugin/sexplib.vim) as well.

**Comment by mmottl** [comment]
Thanks, I have added the changes to the Dune and Sexplib plugin files.

**Comment by cwfoo** [comment]
Fixed in https://github.com/ocaml/vim-ocaml/commit/400bee047d116d1cbe72a479943ec69d5b5bba01
